- name: install samba package
  package:
    name: samba
    state: present

- name: add settings
  blockinfile:
    path: /etc/samba/smb.conf
    block: |
        [media]
        path = "{{ media_dir }}"
        public = yes
        writable = yes
        guest ok = no 
        guest only = no 
  notify: restart samba